on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v5.0.0
      with:
        fetch-depth: 0
    - uses: coursier/cache-action@v6.4.7
    - uses: VirtusLab/scala-cli-setup@v1.9.0
    - run: scala-cli format --check && scala-cli test .
